### ISSUE TITLE
이슈3

### ISSUE THREAD

**Issue by youdaehoon** [stydty-github-project-issue-ect/study_github_project-issue#3]
```[tasklist]
### Tasks
- [ ] https://github.com/stydty-github-project-issue-ect/study_github_project-issue/issues/1
- [ ] https://github.com/stydty-github-project-issue-ect/study_github_project-issue/issues/2
```

**Comment by youdaehoon** [comment]
- [ ]

**Comment by youdaehoon** [comment]
[tasklist]
### Tasks
- [ ] https://github.com/stydty-github-project-issue-ect/study_github_project-issue/issues/1
